# Generated by Django 5.2.4 on 2025-08-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
